# Default values for druid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

#TODO remove quickstart stuff
iapVersion: "imply-1.3.1"
debug: "True"

postgresqlName: "postgresql"

druidSegmentDeepStorage: "druid-deep-storage"

zookeeper:
  Replicas: 3
  Name: zk
postgresql:
  postgresUser: druid
  postgresDatabase: druid
  postgresPassword: secret

nodes:
  coordinator:
    name: "coordinator"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-coordinator
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-coordinator-service
      type: NodePort
      ports:
        - name: coordinator-port
          port: 8081
  overlord:
    name: "overlord"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-overlord
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-overlord-service
      type: NodePort
      ports:
        - name: overlord-port
          port: 8090
  historical:
    name: "historical"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-historical
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-historical-service
      type: ClusterIP
      ports:
        - name: historical-port
          port: 8083
  broker:
    name: "broker"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-broker
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-broker-service
      type: NodePort
      ports:
        - name: broker-port
          port: 8082
  tranquility:
    name: "tranquility"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-tranquility
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-tranquility-service
      type: NodePort
      ports:
        - name: tranquility-port
          port: 8200
  pivot:
    name: "pivot"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-pivot
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-pivot-service
      type: NodePort
      ports:
        - name: pivot-port
          port: 9095
  middlemanager:
    name: "middlemanager"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-middlemanager
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-middlemanager-service
      type: NodePort
      ports:
        - name: middlemanager-port
          port: 8091

image:
  historical:
    repository: jkaralus/druid8s-historical
    tag: latest
    pullPolicy: IfNotPresent
  quickstart:
    repository: jkaralus/druid8s-quickstart
    tag: latest
    pullPolicy: IfNotPresent
service:
  historical:
    name: historical
    type: ClusterIP
    externalPort: 8083
    internalPort: 8083
  quickstart:
    name: quickstart
    type: NodePort
    port: 9095
  #TODO remove ulgy hotfix
  type: NodePort





resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

